function generateTemplate(input: string) {
  return [
    '// @ts-nocheck',
    '// this file is generated by farm-plugin-auto-routes',
    `import React from 'react';`,
    '',
    `const routes = ${input};`,
    '',
    'export default routes;',
    '',
  ].join('\n');
}

export function resolveReact() {
  return {
    suffix: 'tsx|ts|jsx|js',
    generateTemplate,
  };
}
