function generateTemplate(input: string) {
  return [
    '// @ts-nocheck',
    '// this file is generated by webpack-plugin-auto-routes',
    '// do not change anytime!',
    `import React from 'react';`,
    '',
    `const routes = ${input};`,
    '',
    'export default routes;',
    '',
  ].join('\n');
}

function isPageFile(filePath: string) {
  return /.(t|j)sx?$/.test(filePath);
}

function isLayoutFile(filePath: string) {
  return /layouts\/index.(t|j)sx?$/.test(filePath);
}

export function resolveReact() {
  return {
    suffix: 'tsx|ts|jsx|js',
    isPageFile,
    isLayoutFile,
    generateTemplate,
  };
}
