function generateTemplate(input: string) {
  return [
    '// @ts-nocheck',
    '// this file is generated by farm-plugin-auto-routes',
    '',
    `const routes = ${input};`,
    '',
    'export default routes;',
    '',
  ].join('\n');
}

export function resolveVue() {
  return {
    suffix: 'vue',
    generateTemplate,
  };
}
