// this file is generated by webpack-plugin-auto-routes
// do not change anytime!
import React from 'react';

export function getRoutes() {
  const routes = {'home':{'path':'/home','id':'home','name':'home_page_home','title':'首页'},'login':{'path':'/login','id':'login','name':'login','parentId':'@@global-layout'},'@@global-layout':{'path':'/','id':'@@global-layout','name':'@@global-layout','isLayout':true}};
  return {
    routes,
    routeComponents: {
      'home':React.lazy(() => import(/* webpackChunkName: "src__pages__home__index" */ '../pages/home/index.jsx')),
'login':React.lazy(() => import(/* webpackChunkName: "src__pages__login__index" */ '../pages/login/index.jsx')),
'@@global-layout':React.lazy(() => import(/* webpackChunkName: "src__layouts__index" */ '../layouts/index.jsx'))
    },
  };
}
