// this file is generated by webpack-plugin-auto-routes
// do not change anytime!
import React, { Suspense } from 'react';

function withLazyLoad(LazyComponent) {
  const lazyComponentWrapper = (props) => (
    <Suspense fallback={props.loadingComponent}>
      <LazyComponent {...props} />
    </Suspense>
  );
  return lazyComponentWrapper;
}

export function getRoutes() {
  const routes = {'404':{'path':'/404','id':'404','name':'404'},'home-$id':{'path':'/home/:id','id':'home-$id','name':'home-$id','parentId':'@@global-layout'},'home':{'path':'/home','id':'home','name':'home_page_home','title':'首页','parentId':'@@global-layout'},'login':{'path':'/login','id':'login','name':'login','parentId':'@@global-layout'},'@@global-layout':{'path':'/','id':'@@global-layout','name':'@@global-layout','isLayout':true}};
  return {
    routes,
    routeComponents: {
      '404': withLazyLoad(React.lazy(() => import(/* webpackChunkName: "src__pages__404" */ '../pages/404.jsx'))),
'home-$id': withLazyLoad(React.lazy(() => import(/* webpackChunkName: "src__pages__home__$id" */ '../pages/home/$id.jsx'))),
'home': withLazyLoad(React.lazy(() => import(/* webpackChunkName: "src__pages__home__index" */ '../pages/home/index.jsx'))),
'login': withLazyLoad(React.lazy(() => import(/* webpackChunkName: "src__pages__login__index" */ '../pages/login/index.jsx'))),
'@@global-layout': withLazyLoad(React.lazy(() => import(/* webpackChunkName: "src__layouts__index" */ '../layouts/index.jsx')))
    },
  };
}
