// this file is generated by webpack-plugin-auto-route
// do not change any time!
import React, { Suspense } from 'react';
import CustomLoading from '../loading';

function withLazyLoad(LazyComponent) {
  const lazyComponentWrapper = (props) => (
    <Suspense fallback={<CustomLoading />}>
      <LazyComponent {...props} />
    </Suspense>
  );

  return lazyComponentWrapper;
}

export function getRoutes() {
  const routes = {'home-me':{'path':'/home/me','id':'home-me','name':'home-me','title':'首页的我----','parentId':'@@global-layout'},'home':{'path':'/home','id':'home','name':'home_page_home','title':'首页','parentId':'@@global-layout'},'login':{'path':'/login','id':'login','name':'login'},'@@global-layout':{'path':'/','id':'@@global-layout','name':'@@global-layout','isLayout':'true'}};
  return {
    routes,
    routeComponents: {
      'home-me':withLazyLoad(React.lazy(() => import(/* webpackChunkName: "src__pages__home__me" */ '../pages/home/Me.jsx'))),
'home':withLazyLoad(React.lazy(() => import(/* webpackChunkName: "src__pages__home__index" */ '../pages/home/index.jsx'))),
'login':withLazyLoad(React.lazy(() => import(/* webpackChunkName: "src__pages__login__index" */ '../pages/login/index.jsx'))),
'@@global-layout':withLazyLoad(React.lazy(() => import(/* webpackChunkName: "src__layouts__index" */ '../layouts/index.jsx')))
    },
  };
}
